SELECT
        EQP_ASSMBL.ASSMBL_CD AS FLEET,
        -- ACFT_IAR_NEW.AC_REG_CD,
        -- INV_INV.SERIAL_NO_OEM,
        CORR_TASK_SS.BARCODE_SDESC AS CORR_BARCODE,
        FAULT_EVENT.ACTUAL_START_DT AS FAULT_FOUND_DATE,
        SD_FAULT.FAULT_SOURCE_CD AS FAULT_SOURCE,
        -- DEP.LOC_CD AS DEPARTURE_LOCATION,
        sd_fault.fault_log_type_cd AS LOGBOOK_TYPE,
        INV_LOC.LOC_CD AS WRK_PKG_LOC,
        FAULT_EVENT.EVENT_SDESC AS FAULT_NAME,
        FAULT_EVENT.EVENT_LDESC AS FAULT_SDESC,
        SCHED_ACTION.ACTION_LDESC AS CORRECTIVE_ACTION,
        -- FLIGHT.LEG_NO AS TASK_STATUS_CODE.EVENT_STATUS_DB_IDFLIGHT,
        -- FLIGHT.OFF_DT AS FLIGHT_UP_DT,
        FL_LEG_DISRUPT.MAINT_DELAY_TIME_QT,
FOUND_ON_EVENT.EVENT_SDESC AS TASK_NAME,
FOUND_ON_TASK.BARCODE_SDESC AS TASK_BARCODE,
TASK_EVENT.EVENT_DT AS COMPLETION_DT,
        -- ARR.LOC_CD AS ARRIVAL_LOCATION,
-- FAULT_STATUS_CODE.USER_STATUS_CD AS FAULT_STATUS,
        SCHED_ACTION.ACTION_DT AS ACTION_DT,
        -- TO_CHAR(SCHED_ACTION.ACTION_DT, 'DD/MM/YYYY HH24:MI:SS') AS "Dt Corrective Action",
        -- TO_CHAR(SCHED_ACTION.ACTION_DT, 'HH24:MI:SS AM') AS "Corrective Action Time",
        ---SCHED_ACTION.REVISION_USER AS PERFORMED_BY,
        EQP_ASSMBL_BOM.ASSMBL_BOM_CD AS ATA,
FAULT_EVENT.DOC_REF_SDESC AS LOGPAGE,
WORK_PKG_SCHED_STASK.BARCODE_SDESC AS WORK_PKG_BARCODE,
        SD_FAULT.FAIL_SEV_CD AS FAULT_SEVERITY,
        FL_LEG_DISRUPT.DISRUPTION_DESC AS DISRUPTION_ID

FROM
        SD_FAULT
      INNER JOIN EVT_EVENT FAULT_EVENT ON
        SD_FAULT.FAULT_DB_ID = FAULT_EVENT.EVENT_DB_ID AND
        SD_FAULT.FAULT_ID    = FAULT_EVENT.EVENT_ID
      --FIXED
      INNER JOIN SCHED_STASK CORR_TASK_SS ON
        CORR_TASK_SS.FAULT_DB_ID = SD_FAULT.FAULT_DB_ID AND
        CORR_TASK_SS.FAULT_ID = SD_FAULT.FAULT_ID
      INNER JOIN EVT_EVENT TASK_EVENT ON
        TASK_EVENT.EVENT_DB_ID = CORR_TASK_SS.SCHED_DB_ID AND
        TASK_EVENT.EVENT_ID    = CORR_TASK_SS.SCHED_ID
      --FIXED 
      LEFT JOIN EVT_EVENT_REL ON
        FAULT_EVENT.EVENT_DB_ID = EVT_EVENT_REL.REL_EVENT_DB_ID AND
        FAULT_EVENT.EVENT_ID    = EVT_EVENT_REL.REL_EVENT_ID AND
        REL_TYPE_CD = 'DISCF'
      --ADDED
      LEFT JOIN SCHED_STASK FOUND_ON_TASK ON
        EVT_EVENT_REL.EVENT_DB_ID = FOUND_ON_TASK.SCHED_DB_ID AND
        EVT_EVENT_REL.EVENT_ID    = FOUND_ON_TASK.SCHED_ID
      LEFT JOIN EVT_EVENT FOUND_ON_EVENT ON
        EVT_EVENT_REL.EVENT_DB_ID = FOUND_ON_EVENT.EVENT_DB_ID AND
        EVT_EVENT_REL.EVENT_ID    = FOUND_ON_EVENT.EVENT_ID
      LEFT JOIN EVT_EVENT WORK_PKG_EVENT ON
        WORK_PKG_EVENT.EVENT_DB_ID = TASK_EVENT.H_EVENT_DB_ID AND
        WORK_PKG_EVENT.EVENT_ID    = TASK_EVENT.H_EVENT_ID
      LEFT JOIN SCHED_STASK WORK_PKG_SCHED_STASK ON
        WORK_PKG_SCHED_STASK.SCHED_DB_ID = WORK_PKG_EVENT.EVENT_DB_ID AND
        WORK_PKG_SCHED_STASK.SCHED_ID    = WORK_PKG_EVENT.EVENT_ID AND
        WORK_PKG_SCHED_STASK.TASK_CLASS_CD in ('CHECK','RO')
      LEFT OUTER JOIN SCHED_ACTION ON
        CORR_TASK_SS.SCHED_DB_ID = SCHED_ACTION.SCHED_DB_ID AND
        CORR_TASK_SS.SCHED_ID =  SCHED_ACTION.SCHED_ID
      LEFT JOIN EVT_INV ON
        EVT_INV.EVENT_DB_ID = FAULT_EVENT.EVENT_DB_ID AND
        EVT_INV.EVENT_ID    = FAULT_EVENT.EVENT_ID
      -- LEFT JOIN INV_INV ON
      --   INV_INV.INV_NO_DB_ID = EVT_INV.H_INV_NO_DB_ID AND
      --   INV_INV.INV_NO_ID    = EVT_INV.H_INV_NO_ID
      -- LEFT JOIN INV_AC_REG ON
      --   INV_INV.INV_NO_DB_ID = INV_AC_REG.INV_NO_DB_ID AND
      --   INV_INV.INV_NO_ID = INV_AC_REG.INV_NO_ID
      -- LEFT JOIN INV_INV ACFT_II_NEW ON
      --   ACFT_II_NEW.INV_NO_DB_ID = CORR_TASK_SS.MAIN_INV_NO_DB_ID AND
      --   ACFT_II_NEW.INV_NO_ID    = CORR_TASK_SS.MAIN_INV_NO_ID
      -- LEFT JOIN INV_AC_REG ACFT_IAR_NEW ON
      --   ACFT_IAR_NEW.INV_NO_DB_ID = ACFT_II_NEW.H_INV_NO_DB_ID AND
      --   ACFT_IAR_NEW.INV_NO_ID = ACFT_II_NEW.H_INV_NO_ID
      LEFT JOIN EVT_LOC ON
        EVT_LOC.EVENT_DB_ID = WORK_PKG_EVENT.EVENT_DB_ID AND
        EVT_LOC.EVENT_ID    = WORK_PKG_EVENT.EVENT_ID
      LEFT JOIN INV_LOC ON
        EVT_LOC.LOC_DB_ID = INV_LOC.LOC_DB_ID AND
        EVT_LOC.LOC_ID    = INV_LOC.LOC_ID
      INNER JOIN EQP_ASSMBL ON
        EQP_ASSMBL.ASSMBL_DB_ID = EVT_INV.ASSMBL_DB_ID AND
        EQP_ASSMBL.ASSMBL_CD    = EVT_INV.ASSMBL_CD
      INNER JOIN EQP_ASSMBL_BOM ON
        EQP_ASSMBL_BOM.ASSMBL_DB_ID  = EVT_INV.ASSMBL_DB_ID AND
        EQP_ASSMBL_BOM.ASSMBL_CD     = EVT_INV.ASSMBL_CD AND
        EQP_ASSMBL_BOM.ASSMBL_BOM_ID = EVT_INV.ASSMBL_BOM_ID
      -- INNER JOIN REF_EVENT_STATUS FAULT_STATUS_CODE ON
      --   FAULT_EVENT.EVENT_STATUS_DB_ID = FAULT_STATUS_CODE.EVENT_STATUS_DB_ID AND
      --   FAULT_EVENT.EVENT_STATUS_CD = FAULT_STATUS_CODE.EVENT_STATUS_CD
      -- INNER JOIN REF_EVENT_STATUS TASK_STATUS_CODE ON
      --   TASK_EVENT.EVENT_STATUS_DB_ID = TASK_STATUS_CODE.EVENT_STATUS_DB_ID AND
      --   TASK_EVENT.EVENT_STATUS_CD = TASK_STATUS_CODE.EVENT_STATUS_CD
      -- LEFT OUTER JOIN FL_LEG FLIGHT ON
      --   SD_FAULT.LEG_ID = FLIGHT.LEG_ID
      -- LEFT OUTER JOIN INV_LOC DEP ON
      --   FLIGHT.DEPARTURE_LOC_DB_ID = DEP.LOC_DB_ID AND
      --   FLIGHT.DEPARTURE_LOC_ID = DEP.LOC_ID
      -- LEFT OUTER JOIN INV_LOC ARR ON
      --   FLIGHT.ARRIVAL_LOC_DB_ID = ARR.LOC_DB_ID AND
      --   FLIGHT.ARRIVAL_LOC_ID = ARR.LOC_ID
      LEFT JOIN FL_LEG_DISRUPT ON
        FL_LEG_DISRUPT.SCHED_DB_ID = CORR_TASK_SS.SCHED_DB_ID AND
        FL_LEG_DISRUPT.SCHED_ID = CORR_TASK_SS.SCHED_ID
        
WHERE SD_FAULT.FAULT_SOURCE_CD in ('MECH','PILOT','CABIN','AUTH')

AND WORK_PKG_SCHED_STASK.TASK_CLASS_CD <> 'RO'

ORDER BY SCHED_ACTION.ACTION_ID